export const VOTING_CONTRACT_ADDRESS = import.meta.env.VITE_VOTING_CONTRACT_ADDRESS;

export const VOTING_CONTRACT_ABI = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [{ name: "initialOwner", type: "address" }],
  },
  {
    type: "function",
    name: "MAX_VOTES_PER_DAY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "currentVotingDay",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextResetTimestamp",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "timeUntilReset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "addGame",
    stateMutability: "nonpayable",
    inputs: [{ name: "key", type: "string" }],
    outputs: [{ name: "gameId", type: "uint256" }],
  },
  {
    type: "function",
    name: "setGameActive",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "gameCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getGame",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "key", type: "string" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "gameIdForKey",
    stateMutability: "view",
    inputs: [{ name: "key", type: "string" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getGames",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "gameIds", type: "uint256[]" },
      { name: "keys", type: "string[]" },
      { name: "active", type: "bool[]" },
    ],
  },
  {
    type: "function",
    name: "vote",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "votesRemaining",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUserVotes",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "gameIds", type: "uint256[]" },
      { name: "keys", type: "string[]" },
      { name: "votesPerGame", type: "uint256[]" },
      { name: "votesUsedToday", type: "uint256" },
      { name: "votesLeftToday", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getAllVotes",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "gameIds", type: "uint256[]" },
      { name: "keys", type: "string[]" },
      { name: "votes", type: "uint256[]" },
      { name: "totalVotes", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getAllTimeVotes",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "gameIds", type: "uint256[]" },
      { name: "keys", type: "string[]" },
      { name: "votes", type: "uint256[]" },
      { name: "totalVotes", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "pause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "unpause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "Voted",
    anonymous: false,
    inputs: [
      { name: "voter", type: "address", indexed: true },
      { name: "gameId", type: "uint256", indexed: true },
      { name: "day", type: "uint256", indexed: true },
      { name: "userVotesToday", type: "uint256", indexed: false },
      { name: "gameVotesToday", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GameAdded",
    anonymous: false,
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "key", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "GameActiveSet",
    anonymous: false,
    inputs: [
      { name: "gameId", type: "uint256", indexed: true },
      { name: "active", type: "bool", indexed: false },
    ],
  },
];