export const LEVELSConfig = [
  {
    level: 1,
    name: "Beginner Bay",
    fishType: "RED",
    fishCount: 10,
    fishPts: 70,
    g: 5,
    c: 4,
    p: 0,
    s: 0,
    bs: false,
    r: 6,
    b: 2,
    cr: 3,
    water: "#0CA4FF",
  },
  {
    level: 2,
    name: "Rocky Waters",
    fishType: "BLUE",
    fishCount: 14,
    fishPts: 80,
    g: 7,
    c: 5,
    p: 2,
    s: 0,
    bs: false,
    r: 8,
    b: 3,
    cr: 4,
    water: "#0984e3",
  },
  {
    level: 3,
    name: "Pirate Lagoon",
    fishType: "YELLOW",
    fishCount: 18,
    fishPts: 90,
    g: 7,
    c: 5,
    p: 4,
    s: 0,
    bs: false,
    r: 10,
    b: 4,
    cr: 5,
    water: "#00cec9",
  },
  {
    level: 4,
    name: "Deep Ocean",
    fishType: "PURPLE",
    fishCount: 20,
    fishPts: 100,
    g: 6,
    c: 6,
    p: 3,
    s: 2,
    bs: false,
    r: 12,
    b: 6,
    cr: 6,
    water: "#1e3799",
  },
  {
    level: 5,
    name: "Kraken Territory",
    fishType: "GOLD",
    fishCount: 25,
    fishPts: 110,
    g: 8,
    c: 8,
    p: 5,
    s: 5,
    bs: true,
    r: 14,
    b: 10,
    cr: 8,
    water: "#0c2461",
  },
];

// Per-kind capacity ceilings for the Three.js InstancedMesh pools —
// the max any single level ever spawns, so pools are sized once and
// never need to grow at runtime.
export const MAX_COUNTS = {
  rock: Math.max(...LEVELSConfig.map((c) => c.r)),
  barrel: Math.max(...LEVELSConfig.map((c) => c.b)),
  coral: Math.max(...LEVELSConfig.map((c) => c.cr)),
  greenFish: Math.max(...LEVELSConfig.map((c) => c.g)),
  crab: Math.max(...LEVELSConfig.map((c) => c.c)),
  pirate: Math.max(...LEVELSConfig.map((c) => c.p)),
  shark: Math.max(...LEVELSConfig.map((c) => c.s)),
  tentacle: 16,
  fish: Math.max(...LEVELSConfig.map((c) => c.fishCount)),
  powerupPerType: 4,
  particles: 300,
};